### ISSUE TITLE
v0.9.0 generates wrong CSS

### ISSUE THREAD

**Issue by ModyQyW** [Dunqing/unocss-preset-theme#57]
https://unocss.dev/play/?html=DwEwlgbgBAxgNgQwM5ILwCIAuBTAHpgWgAcAnMAWwRIE90A%2BAKGAHpwI6g&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5JQkWImq0GMACoALDCAxxO3XgOEQxdALQ16jIzDUbJSDAA8Z8TFgCGggDZPseQsTIAKZFRTRToALjgAbSpghUYWCH8ASkpUWLNlKwxAmLTLdQwIoLSS92BSFRgi3JLUEQh3aHDEGtrY0BcoAE8I-gA3Tv8jIwx3I3rGqBMoDu6kyTaS9lbUdlTFtE6Aa2rFtImm3b20mlmegQGoIZGxg6nTkE6u%2BZW05b211ve3pKoAXQ4vyAA&css=Q&options=N4XyA

<img width="518" alt="image" src="https://github.com/Dunqing/unocss-preset-theme/assets/31850793/69faa20e-53aa-4c0f-9ca4-52304d48b29f">

Expected:

```css
/* layer: theme */
:root{--un-preset-theme-colors-primary:var(--el-color-primary);}
.dark{--un-preset-theme-colors-primary:var(--el-color-primary);}
/* layer: default */
.text-primary{color:var(--un-preset-theme-colors-primary);}
```

Or 

```css
/* layer: theme */
:root, .dark {--un-preset-theme-colors-primary:var(--el-color-primary);}
/* layer: default */
.text-primary{color:var(--un-preset-theme-colors-primary);}
```

Or

```css
/* v0.8.1 behavior */
/* layer: default */
.text-primary{color:var(--el-color-primary);}
```

[Reproduction](https://github.com/ModyQyW/unocss-preset-theme-57)

**Comment by ModyQyW** [comment]
0.8.1 works fine.

**Comment by ModyQyW** [comment]
It looks like v0.8.1 has the same issue. 

v0.8.1 generates

```css
/* layer: theme */
.dark .dark,
:root{--un-preset-theme-colors-primary:var(--el-color-primary);}
/* layer: default */
.text-primary{color:var(--un-preset-theme-colors-primary);}
```
