### ISSUE TITLE
v0.9.1 generates wrong css?

### ISSUE THREAD

**Issue by ModyQyW** [Dunqing/unocss-preset-theme#58]
https://unocss.dev/play/?html=DwZwDghgdgBAxgGwiEBeARADxALgC4CmmeAtJgugHyEh7AD040lQA&config=JYWwDg9gTgLgBAbwFBzgEwKYDNgDsMDCEuOA5gDQpxhQYDOGMAqrhJQL5xZQQhwDkAV1YBjOnX5JQkWNVoMYAFQAWGEBi48%2BQ0eIC0Neoz0xV6yUgwAPGfExYAhoIA2d7HkLEyACmSpDCnQAXHAA2lT%2B8owsEN4AlJSokUZKZhi%2BEUmmahghfkkFzsCkyjB5mQWoAEa0DgDWkHgwwYhwVi38AAxgVvzkcHQgIfwA7ABsABw9fXAgaMMAnAsATNP9zqTDAIzLnd29-VbO2yv7-HDsFUnsiZWoaA5QdeV3BTUY9Y24zXltHWf9QbDcZTA6zeYCJarMEbba7AFtY4CLanaYXK6oS53LHXOJUAC6HDxQA&css=Q&options=N4IgLgTghgdgzgMwPYQLYgFwKgGzgUwF8g

<img width="757" alt="image" src="https://github.com/Dunqing/unocss-preset-theme/assets/31850793/74a835b6-dd2a-4337-93f9-d6e493f02682">

It seems that v0.9.1 hasn't generated the css var `--un-preset-theme-breakpoints-xs` but used it.

Am I doing wrong or is this a bug?

**Comment by Dunqing** [comment]
I think it's a bug, the output should contain all used theme configuration

**Comment by ModyQyW** [comment]
After I add the support and want to send a PR, I found out that `Variables do not work inside media queries and container queries. `... 😅 What a life waste...

<img width="631" alt="image" src="https://github.com/Dunqing/unocss-preset-theme/assets/31850793/a34d22c6-9535-48fd-b947-eb1dc3fd2c07">

**Comment by ModyQyW** [comment]
I can think of 3 possibilities.

1. generates

```css
@media (min-width: 0px){
.xs\:text-xl{font-size:1.25rem;line-height:1.75rem;}
}
```

instead of 

```css
@media (min-width: var(--un-preset-theme-breakpoints-xs)){
.xs\:text-xl{font-size:1.25rem;line-height:1.75rem;}
}
```

However, this is unexpected if I want different breakpoints for different themes. Another possible way is [custom media query](https://www.w3.org/TR/mediaqueries-5/#custom-mq) which is not launched for now and can not be used here.

2. ignore generations and let users override in their config files.

3. accept the generation for `:root` and ignore others' generations. I think this one is fine and prefer this one for now.

Which one do you prefer? If I am wrong, please correct me. Thanks! 🙏
